version: '3.7'

services:
  pyramid:
    build: .
    image: backend
    env_file: .env
    command: uwsgi --ini-paste /code/app.ini --py-autoreload 1 --honour-stdin
    volumes:
      - ./backend/code:/code
    ports:
    - 8000:8000

  tornado:
    image: backend
    env_file: .env
    command: python starttornado.py
    volumes:
      - ./backend/code:/code
    ports:
    - 8001:8001

  celery:
    image: backend
    env_file: .env
    command: celery -A startcelery.cel worker --loglevel=info
    volumes:
      - ./backend/code:/code

  mq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    labels:
      - "traefik.enable=false"

  postgres:
      image: postgres:11.2
      volumes:
        - pgdata:/var/lib/postgresql/data
      env_file: .env

volumes:
  pgdata:
